#! /usr/bin/env bash

arg=$1
note=""


if [ -z $arg ]; then
  note=$(ls $MEMODIR | peco)
else
  note=$arg
fi

if [ $note == "-usage" ]; then
  echo "Formats markdown for CLI output."
  echo "[no arguments]         bring up the selector and find a note to view"
  echo "[name of memo]         view the specified memo"
  echo ""
  echo "depends on the following cli tools in path:"
  echo "    https://github.com/peco/peco"
  echo "    http://elinks.or.cz"
  echo "    https://marked.js.org"
  exit 0
fi

note="$MEMODIR/$note"
echo "viewing $note"
echo ""
cat $note | marked | elinks --dump | less
