#memodir = "/home/matt/.config/memo/_posts"
memodir = "/home/matt/Dropbox/Docs/Notes"
editor = "vim"
column = 20
selectcmd = "peco"
#grepcmd = "grep -nH ${PATTERN} ${FILES}"
grepcmd = "sift -i ${PATTERN} ${FILES} || true"
assetsdir = "."
pluginsdir = "/home/matt/.config/memo/plugins"
